# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  pack-for-rpi:
    desc: Pack the project using Velopack
    cmds:
      - pwsh -File build.ps1 PackWithVelopack  --SystemArchitecture arm64 --OperationSystem linux --skip UnitTests E2ETests Format PublishToGitHubWithVelopack CreateVersionLabel
    sources:
      - /**/*.cs
      - /**/*.csproj
    generates:
      - /Velopack/publish/**.*

  install-posh-ssh-module:
    cmds:
      # - pwsh -c "Install-Module -Name Posh-SSH"

  publish-to-rpi:
    summary: >-
      This method builds and packs application for RaspberryPi and uploads it using a single credential prompt.
    vars:
      LOGIN: "mikolaj"
      REMOTE_NAME: "raspberrypi01"
    deps: [install-posh-ssh-module, pack-for-rpi]
    cmds:
      - pwsh -File publish-to-rpi.ps1 -Login "{{.LOGIN}}" -RemoteName "{{.REMOTE_NAME}}"

