# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  pack-for-rpi:
    desc: Pack the project using Velopack
    cmds:
      - pwsh -File build.ps1 PackWithVelopack  --SystemArchitecture arm64 --OperationSystem linux --skip UnitTests E2ETests Format PublishToGitHubWithVelopack CreateVersionLabel
    sources:
      - src/**/*.cs
      - src/**/*.csproj
      - build/**/*.cs
    generates:
      - /Velopack/publish/**.*

  publish-to-rpi:
    summary: >-
      This method builds and packs application for RaspberryPi and uploads it using a single credential prompt.
    vars:
      LOGIN: '{{ .LOGIN | default "mikolaj" }}'
      REMOTE_NAME: '{{ .REMOTE_NAME | default "raspberrypi01" }}'
    deps: [pack-for-rpi]
    cmds:
      - pwsh -File publish-to-rpi.ps1 -Login "{{.LOGIN}}" -RemoteName "{{.REMOTE_NAME}}"

  get-rpi-throttling:
    desc: Get voltage throttling status from RPi
    summary: >-
      This recipe gets information about voltage throttling using the `vcgencmd get_throttled` command.
    vars:
      LOGIN: '{{ .LOGIN | default "mikolaj" }}'
      REMOTE_NAME: '{{ .REMOTE_NAME | default "raspberrypi01" }}'
    cmds:
      - ssh {{.LOGIN}}@{{.REMOTE_NAME}} "vcgencmd get_throttled"